# Generated by Django 4.2.7 on 2023-11-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(help_text='Добавьте фотографию', upload_to='ads/', verbose_name='Изображение'),
        ),
    ]
