# Generated by Django 4.2.7 on 2023-11-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_alter_ads_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='description',
            field=models.TextField(help_text='Описание продукта ...', max_length=999, verbose_name='Описание'),
        ),
    ]
