# Generated by Django 4.2.7 on 2023-11-09 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Категория, к которой принадлежит продукт', max_length=100, verbose_name='Название категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Добавьте фотографию', upload_to='ads_images/', verbose_name='Изображение')),
                ('title', models.CharField(help_text='Напишите название вашего продукта', max_length=100, verbose_name='Название продукта')),
                ('description', models.TextField(help_text='Описание продукта ...', max_length='999', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Цена')),
                ('contact', models.CharField(max_length=100, verbose_name='Связь')),
                ('Address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='ссылка на WhatsApp')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='ссылка на Telegram')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='ссылка на Instagram')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(help_text='Укажите категорию вашего продукта', on_delete=django.db.models.deletion.CASCADE, to='home.category', verbose_name='Категория')),
                ('user', models.ForeignKey(help_text='Пользователь, разместивший объявление', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
